runtime: nodejs16
env: standard
handlers:
  - url: /.*
    script: auto
    secure: always
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
beta_settings:
  cloud_sql_instances: bookstore-api-370618:europe-central2:bookstore-db
