runtime: nodejs16
env: standard
instance_class: F2

env_variables:
  DATABASE_URL: '%DATABASE_URL%'
  JWT_SECRET: '%JWT_SECRET%'
  STAGE: '%_STAGE%'

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 1s
  max_pending_latency: 15s
