runtime: nodejs16
env: standard
instance_class: F2

env_variables:
  DATABASE_URL: '%DATABASE_URL%'
  JWT_SECRET: '%JWT_SECRET%'
  STAGE: '%STAGE%'
  CLOUDINARY_CLOUD_NAME: '%CLOUDINARY_CLOUD_NAME%'
  CLOUDINARY_API_KEY: '%CLOUDINARY_API_KEY%'
  CLOUDINARY_API_SECRET: '%CLOUDINARY_API_SECRET%'

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 1s
  max_pending_latency: 15s
