steps:
  - name: 'node:16.5.0'
    id: Install all dependencies
    entrypoint: npm
    args: ['install']
  - name: 'node:16.5.0'
    id: Build the app
    entrypoint: npm
    args: ['run', 'build']
  substitutions:
    - 'DATABASE_URL=${_DATABASE_URL}'
    - 'JWT_SECRET=${_JWT_SECRET}'
    - 'STAGE=${_STAGE}'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy the app
    args: ['app', 'deploy']
timeout: '1600s'
