steps:
  - name: 'node:16.5.0'
    id: Install all dependencies
    entrypoint: npm
    args: ['install']
  - name: 'ubuntu'
    id: Add environment variables
    args: ['bash', './cloud_env.sh']
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - 'STAGE=${_STAGE}'
  - name: 'node:16.5.0'
    id: Build the app
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/npm'
    id: Run migration
    entrypoint: npx
    env:
      - DATABASE_URL=$_DATABASE_URL_BUILD
    args: ['prisma', 'migrate', 'deploy']
  - name: 'gcr.io/cloud-builders/npm'
    id: Seed db
    entrypoint: npx
    env:
      - DATABASE_URL=$_DATABASE_URL
    args: ['prisma', 'seed']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy the app
    args: ['app', 'deploy']
timeout: '1600s'
