steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: Install all dependencies
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    id: Build the app

    args: ['run', 'build']
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'JWT_SECRET=${_JWT_SECRET}'
timeout: '1600s'
