version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bookstore_1ea5_user
      POSTGRES_PASSWORD: dNOimKgRMZclZUh7yrfpuPHDmHnjcVCG
      POSTGRES_DB: bookstore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  prisma-postgres-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    restart: always
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /usr/src/app/node_modules # anonymous volume for node_modules only
    container_name: ts-node-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    command: npm run dev
volumes:
  postgres-data:
  pgadmin-data:
